source 'http://rubygems.org'

gem 'selenium-webdriver'
gem 'capybara'
gem 'slim'
gem 'faye-websocket'
gem 'sinatra', '2.0.0.beta2', require: 'sinatra/base'
gem 'puma'
gem 'pry'
gem 'coffee-script'
gem 'chromedriver-helper'
gem 'awesome_print'